# Generated by Django 4.0.6 on 2022-12-22 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_room_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='quest',
            new_name='guest',
        ),
    ]
